<h1>Laminas API Tools for Doctrine</h1>

<h3>Laminas API Tools-enabled Module <?= $this->escapeHtml($this->moduleName); ?> has been created.</h3>

<h4>Doctrine Entity to Routes Created</h4>

<table class="table table-striped table-hover">

<?php
foreach($this->results as $entityName => $route) {
?>
<tr>
    <td>
        <?= $this->escapeHtml($entityName); ?>
    </td>
    <td>
        <?= $this->escapeHtml($route); ?>
    </td>
</tr>
<?php
}
?>
</table>
